version: "3.9"
services:
  nginx:
    image: nickchen20/nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
     - ${PWD}/data/html:/usr/share/nginx/html
     - ${PWD}/data/conf.d:/etc/nginx/conf.d
     - ${PWD}/data/certificate:/etc/certificate