version: "3.9"
services:
  nginx:
    image: nickchen20/nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
     - ${PWD}/data/html:/usr/share/nginx/html
     - ${PWD}/data/conf.d:/etc/nginx/conf.d
     - ${PWD}/data/certificate:/etc/certificate
    healthcheck:
      test: ["CMD", "curl", "-f", "https://niq.tw"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s