version: '3'
services:
  nginx:
    container_name: nginx-plain
    image: nginx:1.22
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ${PWD}/data/html:/usr/share/nginx/html
     - ${PWD}/data/conf.d:/etc/nginx/conf.d
     - ${PWD}/data/certificate:/etc/certificate