version: '3.9'
services:
  nginx:
    image: nginx:1.22
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/data/html:/usr/share/nginx/html
      - ${PWD}/data/conf.d:/etc/nginx/conf.d
      - ${PWD}/data/certificate:/etc/certificate